from datetime import datetime
from typing import Literal, Optional
from pydantic import BaseModel, ConfigDict, Field


class StepMetrics(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)
    step: int = Field(..., description="1-index iteration number")
    input_tokens: int = Field(
        ..., description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(
        ..., description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(
        ..., description="wall-clock time for the LLM API call in ms")
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp")
    api_url: str = Field(default="",
                         description="Base URL of the LLM API endpoint")
    model_name: str = Field(
        default="", description="Model identifier used for this step")
    llm_output: str = Field(
        default="", description="Raw LLM response before parsing")
    extracted_code: str = Field(
        default="", description="Python code extracted from the LLM output")
    sandbox_input: str = Field(
        default="", description="Python code sent to sandbox excution")
    sandbox_output: str = Field(
        default="", description="Sandbox stdout/stderr/result")
    retries: int = Field(
        default=0, 
        description="Number of retries before successful API response")


class SolutionOutput(BaseModel):
    model_config = ConfigDict(extra="forbid", validate_assignment=True)
    task_id: str
    benchmark: Literal["mbpp", "swebench"]
    success: bool
    solution: str = Field(
        default="", description="Final code solution or git patch")
    system_prompt: str = Field(
        default="", description="Full system prompt sent to the model")
    iterations: int
    total_requests: int
    total_input_tokens: int
    total_output_tokens: int
    total_time_seconds: float
    steps: list[StepMetrics] = Field(default_factory=list)
    error: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())